### ISSUE TITLE
panic: read content of packet fail: unexpected EOF

### ISSUE THREAD

**Issue by tomlister** [Tnze/go-mc#124]
Hi.

I'm trying to adapt the server example to 1.17.1

When I read the handshake packet, the server errors out.
`panic: read content of packet fail: unexpected EOF`
Code is pretty much the same as the example. Slowly going through and reimplementing it.

**Comment by comblock** [comment]
I'm trying the same thing (porting the example server to 1.17.1) and I also get the clientside error: 
`Internal Exception: io.netty.handler.codec.DecoderException: The received encoded string buffer length is longer than maximum allowed (99 > 64)`
however, the error message is very inconsistent, sometimes I get an EOF error and sometimes I get 
`Login failed on sending PlayerPositionAndLookClientbound because of: write tcp 127.0.0.1:25565->127.0.0.1:60616: wsasend: An established connection was aborted by the software in your host machine.`
or:
`Login failed on joinGame because of: write tcp 127.0.0.1:25565->127.0.0.1:60278: wsasend: An established connection was aborted by the software in your host machine.`

the two other errors simply mean that the client closed the connection which of course, has to do with the clientside error

**Comment by Tnze** [comment]
I think the Login protocol is changed in 1.17.1.

**Comment by comblock** [comment]
It did, I adjusted the Join Game packet to work with it:
`func joinGame(conn net.Conn) error {
	DimensionCodec, err := os.ReadFile("dimension_codec.nbt")
	if err != nil {
		log.Fatalln(err)
	}

	Dimension, err := os.ReadFile("dimension.nbt")
	if err != nil {
		log.Printf("Error while encoding DimensionCodec: %v", err)
	}

	return conn.WritePacket(pk.Marshal(JoinGame,
		pk.Int(0),          // EntityID
		pk.Boolean(false),  // Is hardcore
		pk.UnsignedByte(1), // Gamemode
		pk.Byte(1),         // Previous Gamemode
		pk.VarInt(1),       // World Count
		pk.Ary{Len: 1, Ary: []pk.Identifier{pk.Identifier("world")}}, // World Names
		pk.NBT(DimensionCodec),     // Dimension codec
		pk.NBT(Dimension),          // Dimension
		pk.Identifier("world"),     // World Name
		pk.Long(0),                 // Hashed Seed
		pk.UnsignedByte(MaxPlayer), // Max Players
		pk.VarInt(15),              // View Distance
		pk.Boolean(false),          // Reduced Debug Info
		pk.Boolean(true),           // Enable respawn screen
		pk.Boolean(false),          // Is Debug
		pk.Boolean(true),           // Is Flat
	))
}
`
I also adjusted the Player Positition and Look (clientbound) packet `if err := conn.WritePacket(pk.Marshal(PlayerPositionAndLookClientbound,
		// https://wiki.vg/Protocol#Player_Position_And_Look_.28clientbound.29
		pk.Double(0), pk.Double(0), pk.Double(0), // XYZ
		pk.Float(0), pk.Float(0), // Yaw Pitch
		pk.Byte(0),        // flags
		pk.VarInt(0),      // TP ID
		pk.Boolean(false), // Dismount vehicle
	)); err != nil {
		log.Printf("Login failed on sending PlayerPositionAndLookClientbound because of: %v", err)
		return
	}`
