### ISSUE TITLE
[Dim] Chunk Loading Manager

### ISSUE THREAD

**Issue by Tnze** [Tnze/go-mc#192]
Current SimpleDim implement a basic dimension provider that read all chunks from file, and send all of them to players when they join the game.

The problem is the Dim is static and cannot increase its size. No chunk can be creating and the client must load the hole world at one time.

A dynamic chunk loading logic should be add to the Dim implementation. When players are moving, we unload the chunks getting far and load the chunks getting in.

**Comment by maxsupermanhd** [comment]
Here is my implementation of dynamic chunkloading <https://github.com/maxsupermanhd/WebChunk/blob/master/viewer/chunk.go>

**Comment by Tnze** [comment]
Thank you. Very good idea

And I noticed you may want to use `x >> 4` instead of `x / 16` for support negative coordinate.

**Comment by maxsupermanhd** [comment]
I would not call it a very good idea because it only checks someone's render circle/square/elephant on timer, not on movement packet, that introduces non-responsiveness if player is moving fast enough and even scares me sometimes that it crashed or something.
Also want to somehow indicate missing chunk, this is an actual problem to somehow visualize those. One idea is to have floating entity with nametag that is always at player's Y level that says `Chunk <x>:<z>(<chunkid>) not found` or something similar, maybe particles on chunkborder.
