### ISSUE TITLE
1.19.2 support / documentation on how to maintain

### ISSUE THREAD

**Issue by HonbraDev** [Tnze/go-mc#215]
**Is your feature request related to a problem? Please describe.**
I would like to use go-mc on versions 1.19.2 and above, however, I do not know how to generate the data necessary to use it.

**Describe the solution you'd like**
The maintainer adds 1.19.2 support or explains how to generate and maintain the library to smooth-brained people like me.

**Describe alternatives you've considered**
Mineflayer

**Comment by Tnze** [comment]
👀

**Comment by Tnze** [comment]
There is no a generic way to generating all data. The data used in go-mc comes from multiple sources.

`lang` is downloaded and converted from Mojang's server.

`blocks.nbt` is generated by a short java code exporting data from server.jar

Some older data is related on PrismarineJS/minecraft-data and is planted to be removed because they are not likely to update timely.
