### ISSUE TITLE
Update to 1.20.04

### ISSUE THREAD

**Issue by Terminal1337** [Tnze/go-mc#271]
2024/01/19 10:20:14 bot: disconnect error: disconnect because: Incompatible client! Please use 1.20.4

A writeup on how to add support from custom versions client side
or if you can update it, it would be great.

Thank you

**Comment by Tnze** [comment]
Sorry, I have no time to update it these months. But these is the steps to upgrade this library for newer Minecraft:

1. Update `data` package, mainly `packetid` and `langs`. One is gotten by a java script and update manually. And the second one can be automatically updated by go generate.
2. Update `level` package, for correctly decode block infos. Update two nbt file and run the go generate.
3. Update protocol numbers in `bot/mcbot.go`, which can be known from wiki.vg
4. Run the "daze" example, test if it can login to vanilla server. If it did, congratulations. Otherwise, check if mojang changed the protocol.

**Comment by brngle** [comment]
Can you please provide an example for how you run the various java scripts for extracting this data? Thanks.

**Comment by Tnze** [comment]
You need to use the project named MCP-reborn or Yarn.

**Comment by Tnze** [comment]
https://github.com/Hexeption/MCP-Reborn

It supports 1.20.2, but I can see there is a PR for 1.20.4
