### ISSUE TITLE
How to use these protocol packages to implement the original Minecraft vanilla server

### ISSUE THREAD

**Issue by earth-hotfix** [Tnze/go-mc#93]
enumerate which modules are included in a complete vanilla server?

**Comment by Tnze** [comment]
If you want to implement a server by yourself, **all sub-packages** except `bot` will help you. Although these packages do a lot of underlying work, you still have a lot of work to do in order to implement a vanilla like server, such as **terrain generation**, **biological AI**, etc. which is not contained in go-mc at present.

You know, it's very responsible to implement a complete game server, not just the two I mentioned above. My suggestion is that you can start with a simple chat server, do some message forwarding and player management, and then slowly add functions to make it closer to the original server. Basically, a server will create a **World** and **Update** it in every **tick**, and allow players play in it.

`go-mc` only do the basic things like "create a secret connection" or "decode a chat message", which can help you develop your client or server. But the core logic and program architecture are still up to you.
